// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDieqHSQJi0diMom2HHig9DGmVoIdBWePQ',
    appId: '1:862471764682:android:a41778b437313b47ced233',
    messagingSenderId: '862471764682',
    projectId: 'haveli-7362d',
    databaseURL: 'https://haveli-7362d-default-rtdb.firebaseio.com',
    storageBucket: 'haveli-7362d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCtAQIe_Xa9bVR7L4AI7O86NqHC_IOi0E',
    appId: '1:862471764682:ios:86c5ba36d711455fced233',
    messagingSenderId: '862471764682',
    projectId: 'haveli-7362d',
    databaseURL: 'https://haveli-7362d-default-rtdb.firebaseio.com',
    storageBucket: 'haveli-7362d.appspot.com',
    androidClientId: '862471764682-li49i644es5gseqh34bre0p2loj47amo.apps.googleusercontent.com',
    iosClientId: '862471764682-e4h4q4i1l2m94vpnq5p35uab4i8c495f.apps.googleusercontent.com',
    iosBundleId: 'com.mtgr.haveli',
  );
}
